version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"       # Staging HTTP → 8081
      - "8444:443"      # Staging HTTPS → 8444
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/comparewarranties.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/comparewarranties.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - chaiz-network
    depends_on:
      - php82

  php82:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - chaiz-network

  db:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - chaiz-db-volume:/var/lib/mysql
    environment:
      TZ: "Africa/Johannesburg"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - chaiz-network
    ports:
      - "3314:3306"

volumes:
  chaiz-db-volume:

networks:
  chaiz-network:
    driver: bridge
