version: "3.8"
services:
    php:
        image: php:8.1-fpm
        container_name: php8_chaiz
        restart: unless-stopped
        volumes:
            - ./chaiz:/var/www/html:delegated
        networks:
            - web-backend
networks:
    web-backend:
        external: true
