version: "3.8"
services:
    php:
        image: php:8.2-fpm
        container_name: php8_chaiz
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - app-network
        expose:
            - "9000"
    nginx:
        image: nginx:alpine
        container_name: nginx_chaiz
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
networks:
    app-network:
        driver: bridge