version: "3.8"
services:
    php:
        image: php:8.2-fpm
        container_name: php8_chaiz
        restart: unless-stopped
        network_mode: host
        volumes:
            - ./:/var/www/html:delegated