version: "3.7"

services:
  nginx-staging:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"      # HTTP
      - "8443:443"     # HTTPS
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx-staging.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/comparewarranties.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/comparewarranties.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - comparewarranties-staging-network
    depends_on:
      - php82-staging
      - db-staging

  php82-staging:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - comparewarranties-staging-network

  db-staging:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - comparewarranties-staging-db-volume:/var/lib/mysql
    environment:
      TZ: "Africa/Johannesburg"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: chaiz_staging
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    networks:
      - comparewarranties-staging-network
    ports:
      - 3314:3306

volumes:
  comparewarranties-staging-db-volume:

networks:
  comparewarranties-staging-network:
    driver: bridge
