version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/comparewarranties.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/comparewarranties.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - chaiz-network
    depends_on:
      - php82
    # deploy:
        #replicas: ${NGINX_REPLICAS:-0}  # Default to 0 replicas (disabled) in production

  php82:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - chaiz-network

  db:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - chaiz-db-volume:/var/lib/mysql
    environment:
      TZ: "Africa/Johannesburg"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - chaiz-network
    ports:
      - 3313:3306

volumes:
  chaiz-db-volume:

networks:
  chaiz-network:
    driver: bridge
