version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_NETWORK_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chaiz-network
    depends_on:
      - php82

  php82:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - chaiz-network

  db:
    image: mariadb:10.5.2
    restart: always
    volumes:
      - chaiz-db-volume:/var/lib/mysql
    environment:
        TZ: "Africa/Johannesburg"
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - chaiz-network
    ports:
      - ${DB_NETWORK_PORT}:3306

volumes:
  chaiz-db-volume:

networks:
  chaiz-network:
    driver: bridge
